from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, date
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import psycopg
import streamlit as st

# ---------------------------
# CONFIG
# ---------------------------
LOC_TRUCK = "Food Truck"
LOC_PREP = "Prep Kitchen"
LOCATIONS = [LOC_TRUCK, LOC_PREP]

ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_FULFILLED = "FULFILLED"
ORDER_STATUS_CANCELLED = "CANCELLED"

PAYMENT_EFTPOS = "EFTPOS"
PAYMENT_CASH = "CASH"


# ---------------------------
# TIME HELPERS
# ---------------------------
def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")


def today_str() -> str:
    return date.today().isoformat()


# ---------------------------
# DB CONNECTION
# ---------------------------
def get_dsn() -> str:
    if "DATABASE_URL" not in st.secrets:
        raise ValueError("Missing DATABASE_URL in Streamlit Secrets (Manage app → Settings → Secrets).")
    return str(st.secrets["DATABASE_URL"]).strip()


@contextmanager
def get_conn():
    # Open a fresh connection per operation (safe + reliable on Streamlit Cloud)
    conn = psycopg.connect(get_dsn(), autocommit=False)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def query_df(sql: str, params: Optional[Tuple[Any, ...]] = None) -> pd.DataFrame:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params or ())
            if cur.description is None:
                return pd.DataFrame()
            cols = [c.name for c in cur.description]
            rows = cur.fetchall()
            return pd.DataFrame(rows, columns=cols)


def exec_sql(sql: str, params: Optional[Tuple[Any, ...]] = None) -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params or ())


def fetch_one(sql: str, params: Optional[Tuple[Any, ...]] = None) -> Optional[Tuple[Any, ...]]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params or ())
            return cur.fetchone()


# ---------------------------
# SCHEMA / INIT
# ---------------------------
def init_db():
    # Tables are created once and never wiped.
    exec_sql(
        """
        CREATE TABLE IF NOT EXISTS items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            unit TEXT NOT NULL,
            par_level DOUBLE PRECISION NOT NULL DEFAULT 0,
            price_nzd DOUBLE PRECISION NOT NULL DEFAULT 0,
            active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS stock (
            item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            location TEXT NOT NULL,
            qty DOUBLE PRECISION NOT NULL DEFAULT 0,
            PRIMARY KEY (item_id, location)
        );

        CREATE TABLE IF NOT EXISTS movements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            location TEXT NOT NULL,
            delta DOUBLE PRECISION NOT NULL,
            reason TEXT NOT NULL,
            ref_type TEXT,
            ref_id BIGINT
        );

        CREATE TABLE IF NOT EXISTS orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            from_location TEXT NOT NULL,
            to_location TEXT NOT NULL,
            status TEXT NOT NULL,
            note TEXT
        );

        CREATE TABLE IF NOT EXISTS order_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
            item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            qty DOUBLE PRECISION NOT NULL
        );

        CREATE TABLE IF NOT EXISTS sales (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            sale_date TEXT NOT NULL,
            payment_method TEXT NOT NULL,
            note TEXT
        );

        CREATE TABLE IF NOT EXISTS sale_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
            menu_id BIGINT NOT NULL,
            sku TEXT NOT NULL,
            name TEXT NOT NULL,
            qty DOUBLE PRECISION NOT NULL,
            unit_price DOUBLE PRECISION NOT NULL,
            line_total DOUBLE PRECISION NOT NULL
        );

        CREATE TABLE IF NOT EXISTS menu_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sku TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            price DOUBLE PRECISION NOT NULL DEFAULT 0,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            sort_order BIGINT NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS menu_recipes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            menu_id BIGINT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
            item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
            qty DOUBLE PRECISION NOT NULL,
            UNIQUE(menu_id, item_id)
        );

        CREATE INDEX IF NOT EXISTS idx_movements_created_at ON movements(created_at);
        CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
        CREATE INDEX IF NOT EXISTS idx_sales_sale_date ON sales(sale_date);
        """
    )


# ---------------------------
# ITEMS + STOCK
# ---------------------------
def ensure_stock_rows_for_item(item_id: int):
    with get_conn() as conn:
        with conn.cursor() as cur:
            for loc in LOCATIONS:
                cur.execute(
                    """
                    INSERT INTO stock(item_id, location, qty)
                    VALUES (%s, %s, 0)
                    ON CONFLICT (item_id, location) DO NOTHING
                    """,
                    (item_id, loc),
                )


def get_items_df(active_only=True) -> pd.DataFrame:
    sql = "SELECT id, name, unit, par_level, price_nzd, active FROM items"
    if active_only:
        sql += " WHERE active = TRUE"
    sql += " ORDER BY name ASC"
    return query_df(sql)


def add_item(name: str, unit: str, par_level: float, price_nzd: float, active: bool = True):
    name = (name or "").strip()
    if not name:
        raise ValueError("Item name cannot be empty.")

    unit = (unit or "unit").strip() or "unit"

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO items(name, unit, par_level, price_nzd, active)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (name) DO UPDATE
                  SET unit = EXCLUDED.unit,
                      par_level = EXCLUDED.par_level,
                      price_nzd = EXCLUDED.price_nzd,
                      active = EXCLUDED.active
                RETURNING id
                """,
                (name, unit, float(par_level), float(price_nzd), bool(active)),
            )
            item_id = int(cur.fetchone()[0])

    ensure_stock_rows_for_item(item_id)


def get_item_id_by_name(name: str) -> Optional[int]:
    row = fetch_one("SELECT id FROM items WHERE name = %s AND active = TRUE", (name,))
    return int(row[0]) if row else None


def adjust_stock(item_id: int, location: str, delta: float, reason: str, ref_type: str = "", ref_id: Optional[int] = None):
    if location not in LOCATIONS:
        raise ValueError("Invalid location.")
    if not (reason or "").strip():
        raise ValueError("Reason is required.")

    ensure_stock_rows_for_item(int(item_id))

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE stock
                SET qty = qty + %s
                WHERE item_id = %s AND location = %s
                """,
                (float(delta), int(item_id), location),
            )
            cur.execute(
                """
                INSERT INTO movements(created_at, item_id, location, delta, reason, ref_type, ref_id)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (now_iso(), int(item_id), location, float(delta), reason, ref_type or None, ref_id),
            )


def get_stock_df() -> pd.DataFrame:
    return query_df(
        """
        SELECT
          s.item_id AS item_id,
          i.name AS name,
          i.unit AS unit,
          i.par_level AS par_level,
          s.location AS location,
          s.qty AS qty
        FROM stock s
        JOIN items i ON i.id = s.item_id
        WHERE i.active = TRUE
        ORDER BY i.name ASC, s.location ASC
        """
    )


def get_stock_pivot() -> pd.DataFrame:
    df = get_stock_df()
    if df.empty:
        return df
    pivot = (
        df.pivot_table(
            index=["item_id", "name", "unit", "par_level"],
            columns="location",
            values="qty",
            aggfunc="sum",
        )
        .reset_index()
    )
    for loc in LOCATIONS:
        if loc not in pivot.columns:
            pivot[loc] = 0.0
    pivot["Below PAR?"] = (pivot[LOC_PREP] < pivot["par_level"]).map({True: "YES", False: ""})
    return pivot


# ---------------------------
# ORDERS
# ---------------------------
def create_order(note: str = "") -> int:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO orders(created_at, from_location, to_location, status, note)
                VALUES (%s, %s, %s, %s, %s)
                RETURNING id
                """,
                (now_iso(), LOC_TRUCK, LOC_PREP, ORDER_STATUS_PENDING, (note or "").strip() or None),
            )
            return int(cur.fetchone()[0])


def add_order_line(order_id: int, item_id: int, qty: float):
    if qty <= 0:
        raise ValueError("Qty must be > 0.")
    exec_sql(
        "INSERT INTO order_lines(order_id, item_id, qty) VALUES (%s, %s, %s)",
        (int(order_id), int(item_id), float(qty)),
    )


def get_orders_df(limit=100) -> pd.DataFrame:
    return query_df(
        """
        SELECT id, created_at, status, COALESCE(note,'') AS note
        FROM orders
        ORDER BY id DESC
        LIMIT %s
        """,
        (int(limit),),
    )


def get_order_lines_df(order_id: int) -> pd.DataFrame:
    return query_df(
        """
        SELECT i.name, i.unit, ol.qty, ol.item_id
        FROM order_lines ol
        JOIN items i ON i.id = ol.item_id
        WHERE ol.order_id = %s
        ORDER BY i.name ASC
        """,
        (int(order_id),),
    )


def set_order_status(order_id: int, status: str):
    exec_sql("UPDATE orders SET status = %s WHERE id = %s", (status, int(order_id)))


def fulfill_order(order_id: int):
    # check status
    row = fetch_one("SELECT status FROM orders WHERE id = %s", (int(order_id),))
    if not row:
        raise ValueError("Order not found.")
    if row[0] != ORDER_STATUS_PENDING:
        raise ValueError(f"Order must be PENDING to fulfill (currently {row[0]}).")

    lines = get_order_lines_df(int(order_id))
    if lines.empty:
        raise ValueError("Order has no lines.")

    # stock check in Prep
    prep = get_stock_df()
    prep_map = {int(r["item_id"]): float(r["qty"]) for _, r in prep.iterrows() if r["location"] == LOC_PREP}

    for _, line in lines.iterrows():
        item_id = int(line["item_id"])
        qty = float(line["qty"])
        have = prep_map.get(item_id, 0.0)
        if have < qty:
            raise ValueError(f"Not enough Prep stock for {line['name']} (have {have}, need {qty})")

    # move stock + log movements
    for _, line in lines.iterrows():
        item_id = int(line["item_id"])
        qty = float(line["qty"])
        adjust_stock(item_id, LOC_PREP, -qty, "Order fulfillment (Prep → Truck)", ref_type="order", ref_id=int(order_id))
        adjust_stock(item_id, LOC_TRUCK, +qty, "Order fulfillment (Prep → Truck)", ref_type="order", ref_id=int(order_id))

    set_order_status(int(order_id), ORDER_STATUS_FULFILLED)


def get_movements_df(limit=300) -> pd.DataFrame:
    return query_df(
        """
        SELECT m.created_at, i.name, m.location, m.delta, m.reason, COALESCE(m.ref_type,'') AS ref_type, COALESCE(m.ref_id::TEXT,'') AS ref_id
        FROM movements m
        JOIN items i ON i.id = m.item_id
        ORDER BY m.id DESC
        LIMIT %s
        """,
        (int(limit),),
    )


# ---------------------------
# MENU
# ---------------------------
def seed_menu_if_empty():
    count = fetch_one("SELECT COUNT(*) FROM menu_items")
    if count and int(count[0]) > 0:
        return

    starters = [
        ("JUST_CHICKEN", "Just Chicken", 20.00, True, 10),
        ("SMALL_CHIPS", "Small Chicken on Chips", 22.00, True, 20),
        ("LARGE_CHIPS", "Large Chicken on Chips", 26.00, True, 30),
        ("BURGER", "Chicken Burger", 20.00, True, 40),
        ("CAULI", "Korean Cauli", 18.00, True, 50),
        ("CHIPS", "Chips", 8.00, True, 60),
    ]
    with get_conn() as conn:
        with conn.cursor() as cur:
            for sku, name, price, active, sort_order in starters:
                cur.execute(
                    """
                    INSERT INTO menu_items(sku, name, price, active, sort_order)
                    VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (sku) DO NOTHING
                    """,
                    (sku, name, float(price), bool(active), int(sort_order)),
                )


def get_menu_items(active_only=True) -> pd.DataFrame:
    sql = "SELECT id, sku, name, price, active, sort_order FROM menu_items"
    if active_only:
        sql += " WHERE active = TRUE"
    sql += " ORDER BY sort_order ASC, name ASC"
    return query_df(sql)


def upsert_menu_items(df: pd.DataFrame):
    with get_conn() as conn:
        with conn.cursor() as cur:
            for _, r in df.iterrows():
                sku = str(r.get("sku", "")).strip()
                name = str(r.get("name", "")).strip()
                if not sku or not name:
                    continue
                price = float(r.get("price", 0.0))
                active = bool(r.get("active", True))
                sort_order = int(r.get("sort_order", 0))

                rid = r.get("id", None)
                if pd.isna(rid):
                    cur.execute(
                        """
                        INSERT INTO menu_items(sku, name, price, active, sort_order)
                        VALUES (%s, %s, %s, %s, %s)
                        ON CONFLICT (sku) DO UPDATE
                          SET name=EXCLUDED.name, price=EXCLUDED.price, active=EXCLUDED.active, sort_order=EXCLUDED.sort_order
                        """,
                        (sku, name, price, active, sort_order),
                    )
                else:
                    cur.execute(
                        """
                        UPDATE menu_items
                        SET sku=%s, name=%s, price=%s, active=%s, sort_order=%s
                        WHERE id=%s
                        """,
                        (sku, name, price, active, sort_order, int(rid)),
                    )


def get_menu_recipe(menu_id: int) -> pd.DataFrame:
    return query_df(
        """
        SELECT mr.id, mr.menu_id, i.id AS item_id, i.name AS item_name, mr.qty
        FROM menu_recipes mr
        JOIN items i ON i.id = mr.item_id
        WHERE mr.menu_id = %s AND i.active = TRUE
        ORDER BY i.name ASC
        """,
        (int(menu_id),),
    )


def upsert_menu_recipe(menu_id: int, df: pd.DataFrame):
    # simplest: delete + insert
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM menu_recipes WHERE menu_id = %s", (int(menu_id),))
            for _, r in df.iterrows():
                try:
                    item_id = int(r["item_id"])
                    qty = float(r["qty"])
                except Exception:
                    continue
                if item_id <= 0 or qty == 0:
                    continue
                cur.execute(
                    """
                    INSERT INTO menu_recipes(menu_id, item_id, qty)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (menu_id, item_id) DO UPDATE SET qty=EXCLUDED.qty
                    """,
                    (int(menu_id), int(item_id), float(qty)),
                )


def get_recipe_map(menu_id: int) -> Dict[int, float]:
    df = query_df("SELECT item_id, qty FROM menu_recipes WHERE menu_id = %s", (int(menu_id),))
    if df.empty:
        return {}
    return {int(r["item_id"]): float(r["qty"]) for _, r in df.iterrows()}


# ---------------------------
# SALES / POS
# ---------------------------
def create_sale(payment_method: str, note: str = "") -> int:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO sales(created_at, sale_date, payment_method, note)
                VALUES (%s, %s, %s, %s)
                RETURNING id
                """,
                (now_iso(), today_str(), payment_method, (note or "").strip() or None),
            )
            return int(cur.fetchone()[0])


def add_sale_line(sale_id: int, menu_id: int, sku: str, name: str, qty: float, unit_price: float):
    line_total = float(qty) * float(unit_price)
    exec_sql(
        """
        INSERT INTO sale_lines(sale_id, menu_id, sku, name, qty, unit_price, line_total)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        """,
        (int(sale_id), int(menu_id), sku, name, float(qty), float(unit_price), float(line_total)),
    )


def get_today_sales_summary() -> Tuple[pd.DataFrame, pd.DataFrame]:
    df = query_df(
        """
        SELECT s.sale_date, s.payment_method, sl.sku, sl.name, sl.qty, sl.line_total
        FROM sales s
        JOIN sale_lines sl ON sl.sale_id = s.id
        WHERE s.sale_date = %s
        """,
        (today_str(),),
    )
    if df.empty:
        return (
            pd.DataFrame(columns=["sale_date", "payment_method", "total"]),
            pd.DataFrame(columns=["sku", "name", "qty", "total"]),
        )

    pay = (
        df.groupby(["sale_date", "payment_method"], as_index=False)["line_total"]
        .sum()
        .rename(columns={"line_total": "total"})
    )
    item = (
        df.groupby(["sku", "name"], as_index=False)
        .agg(qty=("qty", "sum"), total=("line_total", "sum"))
        .sort_values("total", ascending=False)
    )
    return pay, item


def record_pos_sale(menu_row: pd.Series, qty: float, payment_method: str, note: str = "") -> int:
    if qty <= 0:
        raise ValueError("Qty must be > 0.")

    menu_id = int(menu_row["id"])
    sku = str(menu_row["sku"])
    name = str(menu_row["name"])
    price = float(menu_row["price"])

    recipe = get_recipe_map(menu_id)
    if not recipe:
        raise ValueError("This menu item has no recipe yet. Add it in Menu Admin.")

    sale_id = create_sale(payment_method=payment_method, note=note)
    add_sale_line(sale_id, menu_id, sku, name, float(qty), price)

    for item_id, per_unit in recipe.items():
        total_used = float(per_unit) * float(qty)
        adjust_stock(
            item_id=int(item_id),
            location=LOC_TRUCK,
            delta=-total_used,
            reason=f"POS sale: {name} x{qty}",
            ref_type="sale",
            ref_id=int(sale_id),
        )

    return int(sale_id)


# ---------------------------
# EVENT MODE
# ---------------------------
def forecast_from_revenue(revenue_nzd: float, mix: dict, menu_df: pd.DataFrame):
    revenue_nzd = float(revenue_nzd)
    qty_rows = []
    for mid, share in mix.items():
        row = menu_df.loc[menu_df["id"] == mid]
        if row.empty:
            continue
        price = float(row.iloc[0]["price"])
        if price <= 0:
            continue
        qty_est = (revenue_nzd * float(share)) / price
        qty_rows.append((mid, qty_est))

    ing_totals = {}
    for mid, qty_est in qty_rows:
        recipe = get_recipe_map(int(mid))
        for item_id, per_unit in recipe.items():
            ing_totals[item_id] = ing_totals.get(item_id, 0.0) + (float(per_unit) * float(qty_est))

    return qty_rows, ing_totals


# ---------------------------
# Orders draft state (mobile friendly)
# ---------------------------
def ensure_order_lines_state():
    if "order_lines" not in st.session_state:
        st.session_state["order_lines"] = []


def add_to_order_draft(item_name: str, qty: float):
    ensure_order_lines_state()
    if qty <= 0:
        return
    for line in st.session_state["order_lines"]:
        if line["Item"] == item_name:
            line["Qty"] = float(line["Qty"]) + float(qty)
            return
    st.session_state["order_lines"].append({"Item": item_name, "Qty": float(qty)})


def set_order_draft_from_name_totals(name_totals: dict):
    ensure_order_lines_state()
    st.session_state["order_lines"] = [{"Item": k, "Qty": float(v)} for k, v in name_totals.items() if float(v) > 0]


# ---------------------------
# APP UI
# ---------------------------
st.set_page_config(page_title="JAEJU Ops", page_icon="🍗", layout="wide")

# init DB + seed menu once per session
if "db_inited" not in st.session_state:
    init_db()
    seed_menu_if_empty()
    st.session_state["db_inited"] = True

st.title("JAEJU Stock + POS + Events (Supabase)")

mobile_mode = st.toggle("Mobile mode", value=True)
PAGES = ["POS", "Event Mode", "Orders", "Dashboard", "Adjust Stock", "Menu Admin", "Items", "Movements"]

if mobile_mode:
    page = st.selectbox("Go to", PAGES)
    tabs = None
else:
    tabs = st.tabs(PAGES)
    page = None


# -------- POS --------
if (mobile_mode and page == "POS") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("POS")]
    with container:
        st.subheader("POS (one-tap buttons)")

        menu = get_menu_items(active_only=True)
        if menu.empty:
            st.warning("No active menu items. Go to Menu Admin.")
        else:
            pay = st.segmented_control("Payment", [PAYMENT_EFTPOS, PAYMENT_CASH], default=PAYMENT_EFTPOS)
            qty_mode = st.toggle("Qty mode (sell more than 1)", value=False)
            qty = 1.0
            if qty_mode:
                qty = st.number_input("Qty", min_value=1.0, value=1.0, step=1.0)

            cols = st.columns(2)
            for i, (_, r) in enumerate(menu.iterrows()):
                with cols[i % 2]:
                    label = f"{r['name']}\n${float(r['price']):.0f}"
                    if st.button(label, use_container_width=True):
                        try:
                            sale_id = record_pos_sale(r, float(qty), pay, "")
                            st.toast(f"Sold: {r['name']} (#{sale_id})")
                            st.rerun()
                        except Exception as e:
                            st.error(str(e))

        st.divider()
        st.subheader("Today totals")
        pay_summary, item_summary = get_today_sales_summary()
        total_today = float(pay_summary["total"].sum()) if not pay_summary.empty else 0.0
        eftpos_today = float(pay_summary.loc[pay_summary["payment_method"] == PAYMENT_EFTPOS, "total"].sum()) if not pay_summary.empty else 0.0
        cash_today = float(pay_summary.loc[pay_summary["payment_method"] == PAYMENT_CASH, "total"].sum()) if not pay_summary.empty else 0.0

        c1, c2, c3 = st.columns(3)
        c1.metric("Total", f"${total_today:,.2f}")
        c2.metric("EFTPOS", f"${eftpos_today:,.2f}")
        c3.metric("Cash", f"${cash_today:,.2f}")

        if not item_summary.empty:
            st.dataframe(item_summary, use_container_width=True, hide_index=True)
        else:
            st.info("No sales recorded today yet.")


# -------- Event Mode --------
if (mobile_mode and page == "Event Mode") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Event Mode")]
    with container:
        st.subheader("Event Mode (Revenue → Ingredients → Draft Order)")

        menu = get_menu_items(active_only=True)
        if menu.empty:
            st.warning("No active menu items. Add them in Menu Admin.")
        else:
            event_name = st.text_input("Event name", placeholder="Electric Ave Day 1")
            revenue = st.number_input("Target revenue (NZD)", min_value=0.0, value=10000.0, step=500.0)
            buffer_pct = st.number_input("Safety buffer (%)", min_value=0.0, value=10.0, step=1.0)

            st.markdown("### Menu mix")
            mix_raw = {}
            total = 0.0
            for _, r in menu.iterrows():
                mid = int(r["id"])
                default = int(100 / max(len(menu), 1))
                val = st.slider(f"{r['name']} (%)", 0, 100, default)
                mix_raw[mid] = float(val)
                total += float(val)

            if total <= 0:
                st.warning("Set at least one menu share above 0%.")
            else:
                mix = {k: v / total for k, v in mix_raw.items() if v > 0}

                qty_rows, ing_totals = forecast_from_revenue(revenue, mix, menu)
                ing_totals = {k: v * (1.0 + buffer_pct / 100.0) for k, v in ing_totals.items()}

                items = get_items_df(active_only=True)
                id_to_name = {int(r["id"]): str(r["name"]) for _, r in items.iterrows()}

                name_totals = {}
                for item_id, qty_total in ing_totals.items():
                    if int(item_id) in id_to_name:
                        name_totals[id_to_name[int(item_id)]] = float(qty_total)

                st.markdown("### Estimated qty sold")
                qty_view = []
                for mid, qty_est in qty_rows:
                    row = menu.loc[menu["id"] == mid].iloc[0]
                    qty_view.append({"Menu item": row["name"], "Qty (est)": round(float(qty_est), 1), "Price": float(row["price"])})
                st.dataframe(pd.DataFrame(qty_view), use_container_width=True, hide_index=True)

                st.markdown("### Load sheet (ingredients)")
                load_df = pd.DataFrame(
                    [{"Item": k, "Qty": round(float(v), 2)} for k, v in name_totals.items() if float(v) > 0],
                    columns=["Item", "Qty"],
                ).sort_values("Item")
                st.dataframe(load_df, use_container_width=True, hide_index=True)

                st.download_button(
                    "Download load sheet (CSV)",
                    data=load_df.to_csv(index=False).encode("utf-8"),
                    file_name=f"load_sheet_{(event_name or 'event').replace(' ', '_')}.csv",
                    mime="text/csv",
                )

                if st.button("Send to Orders draft", type="primary"):
                    set_order_draft_from_name_totals(name_totals)
                    st.success("Draft created. Go to Orders tab and press Create order.")


# -------- Orders --------
if (mobile_mode and page == "Orders") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Orders")]
    with container:
        st.subheader("Truck → Prep Kitchen Orders (mobile friendly)")

        items = get_items_df(active_only=True)
        if items.empty:
            st.info("Add items first.")
        else:
            item_names = list(items["name"].tolist())
            ensure_order_lines_state()

            note = st.text_input("Order note (optional)", placeholder="Friday top-up / Event name")

            st.markdown("### Add to order")
            c1, c2, c3 = st.columns([2, 1, 1])
            pick_item = c1.selectbox("Item", item_names, key="order_pick_item")
            pick_qty = c2.number_input("Qty", min_value=0.0, value=1.0, step=0.5, key="order_pick_qty")

            if c3.button("Add", type="primary"):
                if pick_qty <= 0:
                    st.warning("Qty must be > 0")
                else:
                    add_to_order_draft(pick_item, float(pick_qty))
                    st.success("Added.")
                    st.rerun()

            st.divider()
            st.markdown("### Draft order")

            if not st.session_state["order_lines"]:
                st.info("No items in the draft yet.")
            else:
                df = pd.DataFrame(st.session_state["order_lines"])
                edited = st.data_editor(
                    df,
                    num_rows="dynamic",
                    use_container_width=True,
                    hide_index=True,
                    column_config={
                        "Item": st.column_config.SelectboxColumn("Item", options=item_names),
                        "Qty": st.column_config.NumberColumn("Qty", min_value=0.0, step=0.5),
                    },
                    key="order_lines_editor",
                )
                edited["Item"] = edited["Item"].fillna("").astype(str)
                edited["Qty"] = edited["Qty"].fillna(0).astype(float)
                edited = edited[(edited["Item"].str.strip() != "") & (edited["Qty"] > 0)]
                st.session_state["order_lines"] = edited.to_dict(orient="records")

                c1, c2 = st.columns([1, 2])
                if c1.button("Clear draft"):
                    st.session_state["order_lines"] = []
                    st.rerun()

                if c2.button("Create order", type="primary"):
                    try:
                        if not st.session_state["order_lines"]:
                            raise ValueError("Add at least one item to the draft.")
                        order_id = create_order(note=note)
                        for line in st.session_state["order_lines"]:
                            item_id = get_item_id_by_name(line["Item"])
                            if not item_id:
                                raise ValueError(f"Item not found/active: {line['Item']}")
                            add_order_line(order_id, int(item_id), float(line["Qty"]))
                        st.success(f"Order #{order_id} created (PENDING).")
                        st.session_state["order_lines"] = []
                        st.rerun()
                    except Exception as e:
                        st.error(str(e))

        st.divider()
        st.subheader("Manage orders")
        orders = get_orders_df()
        if orders.empty:
            st.info("No orders yet.")
        else:
            st.dataframe(orders, use_container_width=True, hide_index=True)
            order_id = st.number_input("Order ID", min_value=1, step=1, value=int(orders.iloc[0]["id"]))
            lines = get_order_lines_df(int(order_id))
            if not lines.empty:
                st.dataframe(lines[["name", "unit", "qty"]], use_container_width=True, hide_index=True)

            c1, c2 = st.columns(2)
            if c1.button("Fulfill (Prep → Truck)", type="primary"):
                try:
                    fulfill_order(int(order_id))
                    st.success("Fulfilled. Stock moved Prep → Truck.")
                    st.rerun()
                except Exception as e:
                    st.error(str(e))

            if c2.button("Cancel order"):
                set_order_status(int(order_id), ORDER_STATUS_CANCELLED)
                st.success("Cancelled.")
                st.rerun()


# -------- Dashboard --------
if (mobile_mode and page == "Dashboard") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Dashboard")]
    with container:
        st.subheader("Stock snapshot")
        pivot = get_stock_pivot()
        if pivot.empty:
            st.info("No items yet. Add items in Items tab.")
        else:
            st.dataframe(
                pivot[["name", "unit", "par_level", LOC_TRUCK, LOC_PREP, "Below PAR?"]],
                use_container_width=True,
                hide_index=True,
            )


# -------- Adjust Stock --------
if (mobile_mode and page == "Adjust Stock") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Adjust Stock")]
    with container:
        st.subheader("Adjust stock (counts, wastage, deliveries)")
        items = get_items_df(active_only=True)
        if items.empty:
            st.info("Add items first.")
        else:
            item_map = dict(zip(items["name"], items["id"]))

            item_name = st.selectbox("Item", list(item_map.keys()))
            location = st.selectbox("Location", LOCATIONS)
            delta = st.number_input("Delta (+ add / - remove)", value=0.0, step=0.5)
            reason = st.text_input("Reason", placeholder="delivery / wastage / recount")

            if st.button("Apply adjustment", type="primary"):
                try:
                    adjust_stock(int(item_map[item_name]), location, float(delta),
                                 reason=reason.strip() or "Manual adjustment",
                                 ref_type="manual", ref_id=None)
                    st.success("Stock updated.")
                    st.rerun()
                except Exception as e:
                    st.error(str(e))


# -------- Menu Admin --------
if (mobile_mode and page == "Menu Admin") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Menu Admin")]
    with container:
        st.subheader("Menu Admin (edit menu + recipes)")
        st.info("Tip: Do this on a laptop if possible. Mobile works, but it’s slower.")

        menu_df = get_menu_items(active_only=False)
        st.markdown("### Menu items")
        edited_menu = st.data_editor(
            menu_df,
            num_rows="dynamic",
            use_container_width=True,
            hide_index=True,
            column_config={
                "id": st.column_config.NumberColumn("id", disabled=True),
                "sku": st.column_config.TextColumn("sku"),
                "name": st.column_config.TextColumn("name"),
                "price": st.column_config.NumberColumn("price", min_value=0.0, step=0.5),
                "active": st.column_config.CheckboxColumn("active"),
                "sort_order": st.column_config.NumberColumn("sort_order", step=10),
            },
            key="menu_editor",
        )
        if st.button("Save menu items", type="primary"):
            try:
                upsert_menu_items(edited_menu)
                st.success("Menu saved.")
                st.rerun()
            except Exception as e:
                st.error(str(e))

        st.divider()
        st.markdown("### Edit recipe (ingredients per 1 sale)")

        menu_all = get_menu_items(active_only=False)
        if menu_all.empty:
            st.warning("No menu items yet.")
        else:
            pick = st.selectbox("Choose menu item", menu_all["name"].tolist())
            menu_id = int(menu_all.loc[menu_all["name"] == pick].iloc[0]["id"])

            items = get_items_df(active_only=True)
            if items.empty:
                st.warning("Add ingredient items in Items tab first.")
            else:
                id_to_name = {int(r["id"]): str(r["name"]) for _, r in items.iterrows()}
                options = list(id_to_name.keys())

                recipe_df = get_menu_recipe(menu_id)
                if recipe_df.empty:
                    edit_df = pd.DataFrame([{"item_id": int(items.iloc[0]["id"]), "qty": 0.0}], columns=["item_id", "qty"])
                else:
                    edit_df = recipe_df[["item_id", "qty"]].copy()

                edited_recipe = st.data_editor(
                    edit_df,
                    num_rows="dynamic",
                    use_container_width=True,
                    hide_index=True,
                    column_config={
                        "item_id": st.column_config.SelectboxColumn(
                            "Ingredient item",
                            options=options,
                            format_func=lambda x: id_to_name.get(int(x), str(x)),
                        ),
                        "qty": st.column_config.NumberColumn("Qty per sale", step=0.01),
                    },
                    key="recipe_editor",
                )
                if st.button("Save recipe", type="primary"):
                    try:
                        upsert_menu_recipe(menu_id, edited_recipe)
                        st.success("Recipe saved.")
                        st.rerun()
                    except Exception as e:
                        st.error(str(e))


# -------- Items --------
if (mobile_mode and page == "Items") or (not mobile_mode):
    container = st.container() if mobile_mode else tabs[PAGES.index("Items")]
    with container:
        st.subheader("Items")

        with st.expander("Add / Update item", expanded=True):
            name = st.text_input("Item name", placeholder="Chicken thigh diced")
            unit = st.text_input("Unit", placeholder="kg / pcs / L")
            par = st.number_input("PAR level (Prep)", min_value=0.0, value=0.0, step=0.5)
            price = st.number_input("Price NZD
